"""Schema definitions for the thalos_prime.agency module.

Defines WorldState, Goal, Action, Prediction, and GoalStatus used by the
World Model and Active Inference Engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum, auto

AGENCY_SCHEMA_VERSION: str = "1.0"

# Seed XOR salt for agency module — "AGNC" in ASCII hex
AGENCY_SEED_SALT: int = 0x41474E43


class GoalStatus(StrEnum):
    """Lifecycle status of a Goal within the World Model."""

    ACTIVE = auto()
    ACHIEVED = auto()
    ABANDONED = auto()


@dataclass
class Goal:
    """A goal that the system is attempting to achieve."""

    id: str
    goal_text: str
    priority: float
    status: GoalStatus
    created_at: int
    version: str = AGENCY_SCHEMA_VERSION


@dataclass
class Action:
    """A system action: query, ingest, reason, or verify."""

    id: str
    action_type: str
    params: dict[str, str]
    expected_outcome: str
    actual_outcome: str | None
    timestep: int
    version: str = AGENCY_SCHEMA_VERSION


@dataclass
class Prediction:
    """A prediction generated by PredictionEngine from the belief graph."""

    id: str
    prediction_text: str
    basis_entity_ids: list[str]
    confidence: float
    validated: bool | None
    timestep: int
    version: str = AGENCY_SCHEMA_VERSION


@dataclass
class WorldState:
    """The complete observable state of the agency subsystem at a timestep."""

    id: str
    seed: int
    timestep: int
    config_hash: str
    active_goals: list[Goal] = field(default_factory=list)
    action_history: list[Action] = field(default_factory=list)
    prediction_log: list[Prediction] = field(default_factory=list)
    version: str = AGENCY_SCHEMA_VERSION
