"""Cloudflare adapter for infra-synthesis.

Emits ``wrangler.toml`` in ``<out_dir>/`` — the configuration file
consumed by the Cloudflare Wrangler CLI for Workers deployment.

Data Plane adapter: pure file-write; no lifecycle state.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

_WRANGLER_TOML = """\
# wrangler.toml — generated by Thalos Prime infra-synthesis
name = "{worker_name}"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "{account_id}"

[env.production]
name = "{worker_name}-production"

[[rules]]
type = "ESModule"
globs = ["**/*.mjs"]

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "production"
PROJECT_VERSION = "{project_version}"
"""


class CloudflareAdapter:
    """Generates a Cloudflare Wrangler configuration from a validated schema."""

    def generate(self, schema: dict[str, Any], out_dir: Path) -> list[Path]:
        """Write ``wrangler.toml`` to *out_dir*.

        Args:
            schema: Validated infrastructure schema dict.
            out_dir: Root output directory.

        Returns:
            List containing the single :class:`Path` written.

        """
        out_dir.mkdir(parents=True, exist_ok=True)

        project = schema.get("project", {})
        network = schema.get("network", {})

        worker_name = str(project.get("name", "my-worker")).lower().replace(" ", "-").replace("_", "-")
        account_id = str(network.get("cloudflare_account_id", "YOUR_ACCOUNT_ID"))
        project_version = str(project.get("version", "0.0.0"))

        content = _WRANGLER_TOML.format(
            worker_name=worker_name,
            account_id=account_id,
            project_version=project_version,
        )

        wrangler_path = out_dir / "wrangler.toml"
        wrangler_path.write_text(content, encoding="utf-8")

        logger.info("CloudflareAdapter wrote wrangler.toml to '%s'", out_dir)
        return [wrangler_path]


__all__ = ["CloudflareAdapter"]
