"""Docker adapter for infra-synthesis.

Emits a minimal ``Dockerfile`` when ``compute.type == "container"``.
The generated file is a production-ready multi-stage build pattern
that installs Python dependencies and runs the project.

Data Plane adapter: pure file-write; no lifecycle state.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

_DOCKERFILE = """\
# Dockerfile — generated by Thalos Prime infra-synthesis
# Project: {project_name} v{project_version}
# syntax=docker/dockerfile:1

FROM python:{python_version}-slim AS builder

WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -e .

FROM python:{python_version}-slim AS runtime

WORKDIR /app
COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .

ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PORT={port}

EXPOSE {port}

CMD ["python", "-m", "{entrypoint}"]
"""


class DockerAdapter:
    """Generates a minimal Dockerfile when compute type is 'container'."""

    def generate(self, schema: dict[str, Any], out_dir: Path) -> list[Path]:
        """Write ``Dockerfile`` to *out_dir* if ``compute.type == "container"``.

        Args:
            schema: Validated infrastructure schema dict.
            out_dir: Root output directory.

        Returns:
            List containing the :class:`Path` written, or empty list when
            compute type is not ``"container"``.

        """
        compute = schema.get("compute", {})
        if compute.get("type") != "container":
            logger.debug(
                "DockerAdapter: skipping — compute.type is '%s', not 'container'",
                compute.get("type"),
            )
            return []

        out_dir.mkdir(parents=True, exist_ok=True)

        project = schema.get("project", {})
        ci_section = schema.get("ci", {})
        network = schema.get("network", {})

        project_name = str(project.get("name", "my-project"))
        project_version = str(project.get("version", "0.0.0"))
        python_version = str(ci_section.get("python_version", "3.12"))
        port = int(network.get("port", 8080))
        entrypoint = str(
            compute.get("entrypoint", project_name.lower().replace("-", "_"))
        )

        content = _DOCKERFILE.format(
            project_name=project_name,
            project_version=project_version,
            python_version=python_version,
            port=port,
            entrypoint=entrypoint,
        )

        dockerfile_path = out_dir / "Dockerfile"
        dockerfile_path.write_text(content, encoding="utf-8")

        logger.info("DockerAdapter wrote Dockerfile to '%s'", out_dir)
        return [dockerfile_path]


__all__ = ["DockerAdapter"]
