"""GitHub Actions adapter for infra-synthesis.

Emits ``ci.yml`` inside ``<out_dir>/`` — a CI workflow YAML with lint and
test job placeholders that can be dropped into ``.github/workflows/``.

Data Plane adapter: pure file-write; no lifecycle state.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

_CI_WORKFLOW = """\
# ci.yml — generated by Thalos Prime infra-synthesis
# Project: {project_name} v{project_version}
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
      - name: Install dev dependencies
        run: pip install -e ".[dev]"
      - name: Run ruff
        run: ruff check .
      - name: Run mypy
        run: mypy {package_name} --strict

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"
      - name: Install dev dependencies
        run: pip install -e ".[dev]"
      - name: Run pytest
        run: pytest tests -v --cov={package_name} --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
"""


class GitHubActionsAdapter:
    """Generates a GitHub Actions CI workflow from a validated schema."""

    def generate(self, schema: dict[str, Any], out_dir: Path) -> list[Path]:
        """Write ``ci.yml`` to *out_dir*.

        Args:
            schema: Validated infrastructure schema dict.
            out_dir: Root output directory.

        Returns:
            List containing the single :class:`Path` written.

        """
        out_dir.mkdir(parents=True, exist_ok=True)

        project = schema.get("project", {})
        ci = schema.get("ci", {})

        project_name = str(project.get("name", "my-project"))
        project_version = str(project.get("version", "0.0.0"))
        python_version = str(ci.get("python_version", "3.12"))
        package_name = str(ci.get("package_name", project_name.lower().replace("-", "_")))

        content = _CI_WORKFLOW.format(
            project_name=project_name,
            project_version=project_version,
            python_version=python_version,
            package_name=package_name,
        )

        ci_path = out_dir / "ci.yml"
        ci_path.write_text(content, encoding="utf-8")

        logger.info("GitHubActionsAdapter wrote ci.yml to '%s'", out_dir)
        return [ci_path]


__all__ = ["GitHubActionsAdapter"]
