"""OpenTofu adapter for infra-synthesis.

Emits ``main.tf`` inside ``<out_dir>/opentofu/``.
OpenTofu is a community fork of Terraform; the HCL syntax is identical for
basic provider declarations.

Data Plane adapter: pure file-write; no lifecycle state.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

_MAIN_TF = """\
# opentofu/main.tf — generated by Thalos Prime infra-synthesis
# Project : {project_name} v{project_version}
# Compute : {compute_type}

terraform {{
  required_version = ">= 1.6.0"
}}

provider "aws" {{
  region = "{region}"
}}

# Add your OpenTofu resource definitions here.
"""


class OpenTofuAdapter:
    """Generates minimal OpenTofu HCL files from a validated schema."""

    def generate(self, schema: dict[str, Any], out_dir: Path) -> list[Path]:
        """Write OpenTofu main configuration file.

        Args:
            schema: Validated infrastructure schema dict.
            out_dir: Root output directory; file written to ``out_dir/opentofu/``.

        Returns:
            List containing the single :class:`Path` written.

        """
        tofu_dir = out_dir / "opentofu"
        tofu_dir.mkdir(parents=True, exist_ok=True)

        project = schema.get("project", {})
        compute = schema.get("compute", {})
        network = schema.get("network", {})

        content = _MAIN_TF.format(
            project_name=project.get("name", "unnamed"),
            project_version=project.get("version", "0.0.0"),
            compute_type=compute.get("type", "container"),
            region=network.get("region", "us-east-1"),
        )

        main_path = tofu_dir / "main.tf"
        main_path.write_text(content, encoding="utf-8")

        logger.info("OpenTofuAdapter wrote main.tf to '%s'", tofu_dir)
        return [main_path]


__all__ = ["OpenTofuAdapter"]
