"""Terraform adapter for infra-synthesis.

Emits ``provider.tf`` and ``main.tf`` inside ``<out_dir>/terraform/``.
Output is minimal but syntactically valid HCL so that ``terraform init``
can parse it without errors.

Data Plane adapter: pure file-write; no lifecycle state.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

_PROVIDER_TF = """\
terraform {{
  required_version = ">= 1.6.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{region}"
}}
"""

_MAIN_TF = """\
# main.tf — generated by Thalos Prime infra-synthesis
# Project : {project_name} v{project_version}
# Compute : {compute_type}

# Add your resource definitions here.
"""


class TerraformAdapter:
    """Generates minimal Terraform HCL files from a validated schema."""

    def generate(self, schema: dict[str, Any], out_dir: Path) -> list[Path]:
        """Write Terraform provider and main files.

        Args:
            schema: Validated infrastructure schema dict.
            out_dir: Root output directory; files written to ``out_dir/terraform/``.

        Returns:
            List of :class:`Path` objects for every file written.

        """
        tf_dir = out_dir / "terraform"
        tf_dir.mkdir(parents=True, exist_ok=True)

        project = schema.get("project", {})
        compute = schema.get("compute", {})
        network = schema.get("network", {})

        provider_content = _PROVIDER_TF.format(
            region=network.get("region", "us-east-1"),
        )
        main_content = _MAIN_TF.format(
            project_name=project.get("name", "unnamed"),
            project_version=project.get("version", "0.0.0"),
            compute_type=compute.get("type", "container"),
        )

        provider_path = tf_dir / "provider.tf"
        main_path = tf_dir / "main.tf"

        provider_path.write_text(provider_content, encoding="utf-8")
        main_path.write_text(main_content, encoding="utf-8")

        logger.info("TerraformAdapter wrote %d files to '%s'", 2, tf_dir)
        return [provider_path, main_path]


__all__ = ["TerraformAdapter"]
